function [PopulationChange] = PredatorVectorFieldPlotFunc(Prey1Population, ...
                                                          Prey2Population, ...
                                                                Consumption1GrowthRate, ...
                                                                Consumption2GrowthRate, ...
                                                                DeathRate, ...
                                                                PredatorPopulation, ...
                                                                PredationRate1, ...
                                                                PredationRate2)
%UNTITLED4 Summary of this function goes here
%   Detailed explanation goes here
    PopulationChange = (Consumption1GrowthRate.*PredationRate1.*Prey1Population ...
                       + Consumption2GrowthRate.*PredationRate2.*Prey2Population - DeathRate.*PredatorPopulation);
end