function [PredatorPopulation] = PredatorPopulationChange(Population, ...
                                                         TimeStep, ...
                                                         Prey1GrowthConstant,...
                                                         Prey2GrowthConstant,...
                                                         PredatorMortalityRate, ...
                                                         Prey1Population, ...
                                                         Prey2Population)
    PredatorPopulation = TimeStep*(Prey1GrowthConstant*(Population*Prey1Population) + Prey2GrowthConstant*(Population*Prey2Population)-(exp(-PredatorMortalityRate*Population)));
end

