function [PopulationChange] = PredatorVectorFieldPlotFunc(Prey1Population, ...
                                                          Prey2Population, ...
                                                          Consumption1GrowthRate, ...
                                                          Consumption2GrowthRate, ...
                                                          DeathRate, ...
                                                          PredatorPopulation, ...
                                                          PredationRate1, ...
                                                          PredationRate2, ...
                                                          RemovalInterval, ...
                                                          CurrentTime)
%UNTITLED4 Summary of this function goes here
%   Detailed explanation goes here
    PopulationChange =  PredatorPopulation .*(Consumption1GrowthRate.*PredationRate1.*Prey1Population ...
                       + Consumption2GrowthRate.*PredationRate2.*Prey2Population);
    PopulationChange = PopulationChange - DeathRate * PredatorPopulation;
    return
end