[Species1,Species2,Predator] = meshgrid(1:10:100,1:10:100,1:10:100);
PreyGrowthrates = [10.0,5.0];
CompetitionCoefficients = [0.5,0.5];
CarryingCapacities = [100,100];
PredationRates = [0.1,0.1];
PredatorPopulation = 1;
Population1 = PreyVectorFieldPlotfunc(Species1, ...
                                      Species2, ...
                                      PreyGrowthrates(1), ...
                                      PreyGrowthrates(2), ...
                                      CompetitionCoefficients(1), ...
                                      CompetitionCoefficients(2), ...
                                      CarryingCapacities(1), ...
                                      CarryingCapacities(2), ...
                                      Predator, ...
                                      PredationRates(1), ...
                                      PredationRates(2));
Population2 = PreyVectorFieldPlotfunc(Species2, ...
                                      Species1, ...
                                      PreyGrowthrates(2), ...
                                      PreyGrowthrates(1), ...
                                      CompetitionCoefficients(2), ...
                                      CompetitionCoefficients(1), ...
                                      CarryingCapacities(2), ...
                                      CarryingCapacities(1), ...
                                      Predator, ...
                                      PredationRates(2), ...
                                      PredationRates(1));
ConsumptionGrowthRate = [1.0,1.0];
DeathRate = 0.01;
Population3 = PredatorVectorFieldPlotFunc(Species1, ...
                                          Species2, ...
                                          ConsumptionGrowthRate(1), ...
                                          ConsumptionGrowthRate(2), ...
                                          DeathRate, ...
                                          Predator, ...
                                          PredationRates(1), ...
                                          PredationRates(2));
L2 = sqrt(Population1.^2 + Population2.^2);
L3 = sqrt(Population1.^2 + Population2.^2 + Population3.^2);
%quiver(Species1,Species2,Population1,Population2,2,'k')
axis equal tight
[startX,startY,startZ] = meshgrid(1,0:10:100,0:10:100);
verts = stream3(Species1,Species2,Predator,Population1,Population2,Population3,startX,startY,startZ);
lineobj = streamline(verts);
view(3)
quiver3(Species1,Species2,Predator,Population1./L3,Population2./L3,Population3./L3,0.5,"ColorMode","auto")
